
project_id = "siunjhiiaduktoqjxalv"

[functions.confirm-subscription]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.fetch-events]
verify_jwt = false

[functions.setup-cron]
verify_jwt = false

[functions.fetch-events-24h]
verify_jwt = false

[functions.fetch-events-realtime]
verify_jwt = false
